dist: xenial

language: python
python:
  - 3.8

env:
  global:
    # Doctr deploy key for keurfonluu/stochopy
    - secure: "aU3I5ZwjegxEAtVB1VoezelyHuPFlAi1ptjE1rgnZoSNrQf2rN0dRgIcmapYeVGV7rrBSnG1HXnYnQWpbwjmpIi/9q7JJnOFDVvaawqnqkmEOHJnDenbt1wFBzuZxlleskf25qpxvMyWcmfWnWUW0U1mzmGZyXG8yuArHulGoHPhNAo1a0yVjVeQqR9ub+tlbU5lIKDnOERn80oJrlq+wOdLjLhx/P8A781tjrfLt4l9U9q7NaqjXZhvUQc2BLanSeIZUktalUCPfurVqFS4VBajNnp6OjIdi15JuTSreUl1n0/dItQ9zPlOo2a+OlgONPa5qUeOgpAsBg1QOBj0wljmdBsiYaiLVTFPVSmrUsxEH3dNeGRmpF0VMYTvw+D4RSLkfi5NptCqXKsZoqCdH6dYkKjARP5W0devHcFcyU7B3o20yYYl6220agZdrPoyqMk46PyejUV1ATZK9p1RfhxSiiCPluehQYTFlx/ZgqlBzblIZKyx1X26kIHgGuOXmm+2XG3xCVcxpfUeALhyZ/gN+xDcxZSZ1hhAlR0S3aSwW3xLLjwEY89/AZ6w7LNHXYHl+9aAsbTZWABOL9Wu+2/rBCSuy7DuHomxa7FTKFDpHz2AJLubFF0ZchFihxtUm4qobqwOUwB0FoH6mNoSAODJmBb/P6g3MXWs8VeIhI8="

install:
  - pip install .
  - pip install -r doc/requirements.txt

script:
  - set -e
  - sphinx-build -b html doc/source doc/build
  - pip install doctr
  - doctr deploy . --built-docs ./doc/build/